// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwG7jFCFGH9TiBvNh0BkXVZcnQNCBHek',
    appId: '1:247599199257:web:34c7add6137088498a6688',
    messagingSenderId: '247599199257',
    projectId: 'shopping-app-c2864',
    authDomain: 'shopping-app-c2864.firebaseapp.com',
    storageBucket: 'shopping-app-c2864.firebasestorage.app',
    measurementId: 'G-JZF8J4SEQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzPMs1DCqxcUh6xIH-FRurj_-zlu2FdQ',
    appId: '1:247599199257:android:555077b6b1f41c4e8a6688',
    messagingSenderId: '247599199257',
    projectId: 'shopping-app-c2864',
    storageBucket: 'shopping-app-c2864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwoSg3Und91pxyKLEhBfO8Kr6hF3QbB6k',
    appId: '1:247599199257:ios:aa6827bd5ef07e138a6688',
    messagingSenderId: '247599199257',
    projectId: 'shopping-app-c2864',
    storageBucket: 'shopping-app-c2864.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwoSg3Und91pxyKLEhBfO8Kr6hF3QbB6k',
    appId: '1:247599199257:ios:aa6827bd5ef07e138a6688',
    messagingSenderId: '247599199257',
    projectId: 'shopping-app-c2864',
    storageBucket: 'shopping-app-c2864.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwG7jFCFGH9TiBvNh0BkXVZcnQNCBHek',
    appId: '1:247599199257:web:5fcbb1a1f8ae49ac8a6688',
    messagingSenderId: '247599199257',
    projectId: 'shopping-app-c2864',
    authDomain: 'shopping-app-c2864.firebaseapp.com',
    storageBucket: 'shopping-app-c2864.firebasestorage.app',
    measurementId: 'G-Y46EVM9XQ0',
  );
}
